---

- name: "Postgresql | Install | Main"
  apt:
    name: "{{pgdg_base_packages}}"
    state: latest

- name: "Postgresql | Install | Tools"
  apt:
    name: "{{pgdb_tools}}"
    state: latest

- name: "Postgresql | Install | Modules"
  apt:
    name: "postgresql-{{ pgdg_version }}-{{item}}"
  loop: "{{pgdg_extensions}}"

- name: "Postgresql | Install | Postgis"
  apt:
    name:
      - "postgresql-{{ pgdg_version }}-postgis-{{pgdg_postgis_versions}}"
      - "postgresql-{{ pgdg_version }}-postgis-{{pgdg_postgis_versions}}-scripts"
  when: pgdg_postgis_install
