---

- name: "Postgresql | Manage | Create cash hash dir"
  file:
    path: "{{ pgdb_hash_cache_dir }}"
    state: directory
  become: yes

- name: "Postgresql | Manage | Users"
  include_tasks: manage_user.yml
  loop: "{{ pgdg_users }}"
  loop_control:
    loop_var: user

#- meta: end_play

- name: "Postgresql | Manage | Create databases"
  become: true
  become_user: postgres
  postgresql_db:
    encoding: UTF-8
    name: "{{ item.database }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ pgdg_users }}"
  when: item.database is defined

- name: "Postgresql | Manage | DB permissions"
  postgresql_privs:
    db: postgres
    privs: "{{ item.privs | default('ALL') }}"
    type: database
    obj: "{{ item.database }}"
    role: "{{ item.user }}"
    state: "{{ item.state | default('present') }}"
  become: true
  become_user: postgres
  loop: "{{ pgdg_users }}"
  when: item.database is defined

- name: "Postgresql | Manage | in-DB permissions"
  postgresql_privs:
    database: "{{ item.database }}"
    roles: "{{ item.user }}"
    objs: ALL_IN_SCHEMA
    privs: "{{ item.privs | default('ALL') }}"
    state: "{{ item.state | default('present') }}"
  become: true
  become_user: postgres
  loop: "{{ pgdg_users }}"
  when: item.database is defined

- name: "Postgresql | Manage | Extension | Create"
  become: true
  become_user: postgres
  postgresql_ext:
    name: timescaledb
    db: "{{ item.database }}"
  loop: "{{ pgdg_users }}"
  when: item.database is defined
